### ISSUE TITLE
Typo in Oper.java?

### ISSUE THREAD

**Issue by keithc-ca** [cliffclick/aa#27]
https://github.com/cliffclick/aa/blob/19dae3a59debb2c6b7ed7f55f5a231cff75e0631/src/main/java/com/cliffc/aa/Oper.java#L51

Should the line read
```
    char c0 = name.charAt(0), c1 = name.charAt(1);
```
instead? The assert on the next line seems to expect `c0` and `c1` to be different.

**Comment by cliffclick** [comment]
Fixed by 137c65ee1ed1100b6e4d684b2d1c5c99962484ce
